from typing import List, Optional
from pydantic import BaseModel, Field, field_validator


class SourceItem(BaseModel):
    """Citation metadata for a retrieved document chunk."""
    document: str = Field(..., description="Name of the source document")
    page: int = Field(..., description="Page number where the chunk originated (1-indexed)")
    chunk_id: Optional[str] = Field(None, description="Unique identifier for the chunk")
    relevance_score: Optional[float] = Field(None, description="Similarity score or distance metric")
    snippet: Optional[str] = Field(None, description="Brief excerpt from the retrieved text")


class QueryRequest(BaseModel):
    """Payload for asking a question against the document collection."""
    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="User question to be answered using document context",
        examples=["What are the Coffman conditions required for a deadlock?"]
    )
    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        le=20,
        description="Optional override for the number of chunks to retrieve"
    )

    @field_validator("question")
    @classmethod
    def validate_question_not_whitespace(cls, v: str) -> str:
        trimmed = v.strip()
        if not trimmed:
            raise ValueError("Question cannot be empty or contain only whitespace.")
        return trimmed


class QueryResponse(BaseModel):
    """Grounded response generated by the RAG pipeline."""
    answer: str = Field(..., description="Grounded answer synthesized by the LLM from retrieved context")
    sources: List[SourceItem] = Field(default_factory=list, description="List of source citations used")
    model: str = Field(..., description="Identifier of the LLM model that generated the answer")
    retrieval_count: int = Field(..., description="Number of context chunks retrieved")


class HealthResponse(BaseModel):
    """Health status and diagnostic details of the service."""
    status: str = Field(..., description="Overall service health status ('healthy' or 'degraded')")
    environment: str = Field(..., description="Application environment ('development', 'production', etc.)")
    vector_store: dict = Field(..., description="Status and stats of the vector database")
    llm: dict = Field(..., description="Status and reachability of the local Ollama LLM")
    embedding_model: str = Field(..., description="Loaded sentence transformer model name")
